#pragma once

#include <ostream>
#include <string>
#include <unordered_map>

namespace RestAPI{
    enum class BooksGenre{
        kCrime,
        kDetective,
        kScience,
        kPostApocalyptic,
        kDistopia,
        kCyberpunk,
        kFantasy,
        kRomantic,
        kWestern,
        kHorror,
        kClassic,
        kFairyTale,
        kFanFiction,
        kFolklore,
        kHistoricalFiction,
        kHumor,
        kMystery,
        kPictureBook,
        kThriller,
        kEroticFiction,
        kBiograpy,
        kAutobiograpy,
        kEssay,
        kManual,
        kMemoir,
        kReferenceBook,
        kTextbook,
        kAcademicPaper,
        kEncyclopedia,
        kDictionary,
        kPopularScience,
        kPhotograph,
        kTechnicalWriting,
        kCookbook,
    };

    std::unordered_map<BooksGenre, const char*> books_genre_to_string({
        {BooksGenre::kCrime, "crime"},
        {BooksGenre::kDetective, "detective"},
        {BooksGenre::kScience, "science"},
        {BooksGenre::kPostApocalyptic,"post-apocalyptic"},
        {BooksGenre::kDistopia,"distopia"},
        {BooksGenre::kCyberpunk,"cyberpunk"},
        {BooksGenre::kFantasy,"fantasy"},
        {BooksGenre::kRomantic,"romantic"},
        {BooksGenre::kWestern,"western"},
        {BooksGenre::kHorror,"horror"},
        {BooksGenre::kClassic,"classic"},
        {BooksGenre::kFairyTale,"fairy tale"},
        {BooksGenre::kFanFiction,"fan fiction"},
        {BooksGenre::kFolklore,"folklore"},
        {BooksGenre::kHistoricalFiction,"historical fiction"},
        {BooksGenre::kHumor,"humor"},
        {BooksGenre::kMystery,"mystery"},
        {BooksGenre::kPictureBook,"picture book"},
        {BooksGenre::kThriller,"thriller"},
        {BooksGenre::kEroticFiction,"erotic fiction"},
        {BooksGenre::kBiograpy,"biography"},
        {BooksGenre::kAutobiograpy,"autobiography"},
        {BooksGenre::kEssay,"essay"},
        {BooksGenre::kManual,"manual"},
        {BooksGenre::kMemoir,"memoir"},
        {BooksGenre::kReferenceBook,"reference book"},
        {BooksGenre::kTextbook,"textbook"},
        {BooksGenre::kAcademicPaper,"academic paper"},
        {BooksGenre::kEncyclopedia,"encyclopedia"},
        {BooksGenre::kDictionary,"dictionary"},
        {BooksGenre::kPopularScience,"popular science"},
        {BooksGenre::kPhotograph,"photograph"},
        {BooksGenre::kTechnicalWriting,"technical writing"},
        {BooksGenre::kCookbook,"cookbook"},
    });

    std::unordered_map<std::string, BooksGenre> string_to_books_genre({
        {"crime", BooksGenre::kCrime},
        { "detective", BooksGenre::kDetective},
        {"science", BooksGenre::kScience},
        {"post-apocalyptic", BooksGenre::kPostApocalyptic},
        {"distopia", BooksGenre::kDistopia},
        {"cyberpunk", BooksGenre::kCyberpunk},
        {"fantasy", BooksGenre::kFantasy},
        {"romantic", BooksGenre::kRomantic},
        {"western", BooksGenre::kWestern},
        {"horror", BooksGenre::kHorror},
        {"classic", BooksGenre::kClassic},
        {"fairy tale", BooksGenre::kFairyTale},
        {"fan fiction", BooksGenre::kFanFiction},
        {"folklore", BooksGenre::kFolklore},
        {"historical fiction", BooksGenre::kHistoricalFiction},
        {"humor", BooksGenre::kHumor},
        {"mystery", BooksGenre::kMystery},
        {"picture book", BooksGenre::kPictureBook},
        {"thriller", BooksGenre::kThriller},
        {"erotic fiction", BooksGenre::kEroticFiction},
        {"biography", BooksGenre::kBiograpy},
        {"autobiography", BooksGenre::kAutobiograpy},
        {"essay", BooksGenre::kEssay},
        {"manual", BooksGenre::kManual},
        {"memoir", BooksGenre::kMemoir},
        {"reference book", BooksGenre::kReferenceBook},
        {"textbook", BooksGenre::kTextbook},
        {"academic paper", BooksGenre::kAcademicPaper},
        {"encyclopedia", BooksGenre::kEncyclopedia},
        {"dictionary", BooksGenre::kDictionary},
        {"popular science", BooksGenre::kPopularScience},
        {"photograph", BooksGenre::kPhotograph},
        {"technical writing", BooksGenre::kTechnicalWriting},
        {"cookbook", BooksGenre::kCookbook},
    });
}